import { test, expect } from "@playwright/test";

test("test", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("h1")).toContainText("Scheduli");
  await expect(page.getByRole("link", { name: "Download on the App Store" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Get it on Google Play" })).toBeVisible();
  await page.getByRole("link", { name: "here." }).click();
  await expect(page.locator("section")).toContainText("Routine 1");
  await expect(page.locator("section")).toContainText("Routine 1's Events");
  await expect(page.locator("section")).toContainText("Active Days for Routine 1");
  await expect(page.getByText("Name:Start Time:End Time:").first()).toBeVisible();
  await expect(page.getByText("Name:Start Time:End Time:").nth(1)).toBeVisible();
  await page.locator("div:nth-child(4) > .shadow-xl > .flex > button").click();
  await page.getByRole("textbox").nth(4).click();
  await page.getByRole("textbox").nth(4).fill("01:40");
  await page.getByRole("textbox").nth(4).click();
  await page.getByRole("textbox").nth(4).fill("00:40");
  await page.getByRole("textbox").nth(4).click();
  await page.getByRole("textbox").nth(4).click();
  await page.getByRole("textbox").nth(4).press("Tab");
  await page.getByRole("textbox").nth(4).fill("00:00");
  await page.getByRole("textbox").nth(5).click();
  await page.getByRole("textbox").nth(5).fill("11:50");
  await page.getByRole("textbox").nth(5).click();
  await page.getByRole("textbox").nth(5).click();
  await page.getByRole("textbox").nth(5).fill("23:50");
  await page.getByRole("textbox").nth(5).click();
  await page.locator("div").filter({ hasText: "Add Event" }).nth(3).click();
  await page.getByRole("textbox").nth(5).click();
  await page.getByRole("textbox").nth(5).click();
  await page.getByRole("textbox").nth(5).press("Tab");
  await page.getByRole("textbox").nth(5).fill("23:59");
  await expect(page.getByRole("button", { name: "Add Event" })).toBeVisible();
  await page.goto("/");
  await expect(page.getByRole("main")).toContainText("End of Event 1");
  await expect(page.getByRole("main")).toContainText("12:00 AM to 11:59 PM");
  await expect(page.locator("h2")).toContainText("Today's Schedule:");
  await expect(page.locator("tbody")).toContainText("Event 1");
  await expect(page.locator("tbody")).toContainText("12:00 AM");
  await expect(page.locator("tbody")).toContainText("11:59 PM");
});
