name: Test iOS App

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build iOS Simulator App
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: dsnss-projects
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: bunx turbo run build:ios:simulator

      - uses: futureware-tech/simulator-action@v4
        with:
          model: "iPhone 17 Pro"
          wait_for_boot: true

      - name: Install iOS App
        run: bun run --filter @scheduli/mobile install:ios:simulator

      - name: Run iOS Tests
        env:
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 120000
        run: bun run --filter @scheduli/mobile test

      - name: Create Debug Information
        if: failure()
        run: |
          mkdir -p ./debug-info
          cp -r ~/Library/Logs/DiagnosticReports/ ./debug-info/diagnostic-reports
          cp -r ~/Library/Logs/CoreSimulator ./debug-info/simulator-logs
          cp -r apps/mobile/.maestro/recordings ./debug-info/recordings
          cp -r ~/.maestro/tests ./debug-info/maestro-logs

      - name: Upload Debug Information
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: debug-info
          path: ./debug-info/
          if-no-files-found: ignore
          retention-days: 1
