name: Build Android App

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: ./.github/actions/setup
        with:
          java: true

      - name: Install dependencies
        run: bun ci

      - name: Build Android Simulator App
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: dsnss-projects
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: bunx turbo run build:android:simulator
